# Step 4: Import numpy by typing the following code in the notebook and run it by pressing shift + enter

In [1]:
import numpy as np

# Step 5: Create np array of zeroes of size (2, 3) run the following code.

In [2]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# Step 6: Flatten 2D np Array to 1d np array.

In [3]:
ar = np.array([[1, 2, 3], [4, 5, 6]])
ar.ravel()

array([1, 2, 3, 4, 5, 6])

# Step 7: Convert 1D np Array to 2d np array from a python list:

In [4]:
ar = np.array([[1, 2, 3, 4, 5, 6]])
ar.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

# Step 8: Create np array and sort

In [5]:
ar = np.array([1, 3, 4, 6, 5, 2])
ar.sort()
ar

array([1, 2, 3, 4, 5, 6])

# Step 9: Slice an np array to create another array without the first two elements of the original array

In [6]:
ar[2:]

array([3, 4, 5, 6])