# Module 4 - Case Study Problem 1 - Numpy

In [1]:
import numpy as np

def solve():
    y=[]
    for i in range(2):
        y.append(int(input()))
    a=tuple(y)
    b=np.full(a,5)
    return b
print(solve())

3
3
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [2]:
ar1 = np.random.randint(0,9,(3,3)) 
ar2 = np.random.randint(0,9,(3,3))
ar3 = np.random.randint(0,9,(3,3))

def ar_sum():
    ar4 = ar1 + ar2 + ar3
    return ar4

ar_sum()

array([[ 6, 19, 14],
       [20, 13, 13],
       [19, 12, 15]])

In [3]:
ar = np.random.randint(0,100,(3,3))

def top_left(ar,m,n):
    print(ar)
    print(ar[0:m,:n])

top_left(ar,2,2)

[[95 60 18]
 [27 91  1]
 [85 38 23]]
[[95 60]
 [27 91]]


In [4]:
ar = np.random.randint(0,100,(3,3))

def bot_rt(ar,m,n):
    print(ar)
    print(ar[m:,n:])

bot_rt(ar,1,1)

[[64 75 90]
 [72 21 64]
 [85 17 16]]
[[21 64]
 [17 16]]


In [5]:
ar=np.array([1,1,1])

def mn_sd():
    mn = np.mean(ar)
    sd = np.std(ar)
    res = {"Mean":mn,"std_dev":sd}
    return res

mn_sd()

{'Mean': 1.0, 'std_dev': 0.0}