# Module 11 - Dimensionality Reduction - Hands On 2 - Factor Analysis

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import FactorAnalysis as FA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
iris = pd.read_csv(url, names = names)

In [3]:
X = iris.iloc[:,:4].values
Y = iris.iloc[:,4].values

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = .7, random_state = 0)

In [5]:
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)

In [6]:
rfc = RandomForestClassifier(max_depth = 2, random_state = 0)
rfc.fit(X_train, Y_train)
Y_pred = rfc.predict(X_test)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))
print('Accuracy Score:', accuracy_score(Y_test, Y_pred))

[[16  0  0]
 [ 0 13  5]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.72      0.84        18
 Iris-virginica       0.69      1.00      0.81        11

       accuracy                           0.89        45
      macro avg       0.90      0.91      0.88        45
   weighted avg       0.92      0.89      0.89        45

Accuracy Score: 0.8888888888888888


In [7]:
fa = FA(n_components = 1)
X_train = fa.fit_transform(X_train)
X_test = fa.fit_transform(X_test)

In [8]:
rfc = RandomForestClassifier(max_depth = 2, random_state = 0)
rfc.fit(X_train, Y_train)
Y_pred = rfc.predict(X_test)
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))
print('Accuracy Score:', accuracy_score(Y_test, Y_pred))

[[16  0  0]
 [ 0 12  6]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.67      0.80        18
 Iris-virginica       0.65      1.00      0.79        11

       accuracy                           0.87        45
      macro avg       0.88      0.89      0.86        45
   weighted avg       0.91      0.87      0.87        45

Accuracy Score: 0.8666666666666667
