# Module 4 - Assignment 1 - Data Structure

In [1]:
import numpy as np

In [2]:
np.random.randint(2,10,(3,3))

array([[8, 5, 8],
       [6, 3, 8],
       [8, 5, 2]])

In [3]:
def ar_int_float():
    a=int(input('How many elements in the array? '))
    l1=[]
    for i in range (0,a):
        l2=int(input('Enter the elements of the array: '))
        l1.append(l2)
    ar = np.array(l1)
    return ar.astype(float)

ar_int_float()

How many elements in the array? 9
Enter the elements of the array: 1
Enter the elements of the array: 2
Enter the elements of the array: 3
Enter the elements of the array: 4
Enter the elements of the array: 5
Enter the elements of the array: 6
Enter the elements of the array: 7
Enter the elements of the array: 8
Enter the elements of the array: 9


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
ar = np.array([10, 20, 30])
def ar_append():
    ar1 = np.array([40, 50, 60, 70, 80, 90])
    ar_app = np.append(ar,ar1)
    return ar_app

ar_append()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
ar1 = np.random.randint(0, 100, 5)
ar2 = np.random.randint(0, 100, 5)
sumArray = ar1 + ar2
print('Array1 is:', ar1)
print('Array2 is:', ar2)
print('Sum of Array1 and Array2 is:', sumArray)

Array1 is: [56 62 23  7 57]
Array2 is: [91 77 65 40  0]
Sum of Array1 and Array2 is: [147 139  88  47  57]


In [6]:
array1 = np.reshape(np.arange(10,91,10),(3,3))
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
array1[0]

array([10, 20, 30])

In [8]:
array1[2][2]

90